# docker-compose_dev.yml
# Build and run docker containers for web services in development environment
services:
  elasticsearch: 
    build: ./elasticsearch
    image: notebooksearch/elasticsearch:latest
    container_name: notebooksearch_elasticsearch
    volumes: 
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    networks: 
      - search_engine_net
    environment:
      - discovery.type=single-node
      - cluster.name=es_dataserver
      - node.name=es01
      - TAKE_FILE_OWNERSHIP=true 
    ports: 
      - 9200:9200

  postgres:
    build: ./postgres
    image: notebooksearch/postgres:latest
    container_name: notebooksearch_postgres
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/logs:/var/lib/postgresql/logs
    networks: 
      - search_engine_net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=notebooksearch2022
      - POSTGRES_DB=notebooksearch
    ports:
      - 5432:5432

  pgadmin:
    build: ./pgadmin
    image: notebooksearch/pgadmin:latest
    container_name: notebooksearch_pgadmin
    restart: always
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    networks: 
      - search_engine_net
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@notebooksearch.com
      - PGADMIN_DEFAULT_PASSWORD=notebooksearch2022
    depends_on: 
      - postgres
    ports:
      - 5050:80

networks: 
  search_engine_net:
    driver: bridge

