services:
  search_engine_app:
    build: ./search_engine_app
    volumes:
      - ./search_engine_app:/search_engine_app
    networks: 
      - search_engine_net
    depends_on:
      - elasticsearch
      - postgres
    expose: 
      - 7777
    
  elasticsearch: 
    build: ./elasticsearch
    volumes: 
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    networks: 
      - search_engine_net
    environment:
      - discovery.type=single-node
      - cluster.name=es_dataserver
      - node.name=es01
      - TAKE_FILE_OWNERSHIP=true 
    expose: 
      - 9200

  postgres:
    image: postgres:14.5-bullseye
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/logs:/var/lib/postgresql/logs
    networks: 
      - search_engine_net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=notebooksearch2022
      - POSTGRES_DB=notebooksearch
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4:6.14
    restart: always
    volumes:
      - ./postgres/pgadmin:/var/lib/pgadmin
    networks: 
      - search_engine_net
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@notebooksearch.com
      - PGADMIN_DEFAULT_PASSWORD=notebooksearch2022
    depends_on: 
      - postgres
    ports:
      - 5050:80
    
  nginx: 
    build: ./nginx
    volumes: 
      - ./search_engine_app/static:/nginx_server/search_engine_app/static
    networks: 
      - search_engine_net
    depends_on:
      - search_engine_app
    ports: 
      - 80:80

networks: 
  search_engine_net:
    driver: bridge

