services:
  search_engine_app:
    build: ./search_engine_app
    volumes:
      - ./search_engine_app:/search_engine_app
    networks: 
      - search_engine_net
    depends_on:
      - elasticsearch
      - postgres
    expose: 
      - 7777
    
  elasticsearch: 
    build: ./elasticsearch
    volumes: 
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    networks: 
      - search_engine_net
    environment:
      - discovery.type=single-node
      - cluster.name=es_dataserver
      - node.name=es01
      - TAKE_FILE_OWNERSHIP=true 
    expose: 
      - 9200

  postgres:
    # image: postgres:14.5-bullseye
    build: ./postgres
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/logs:/var/lib/postgresql/logs
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=notebooksearch2022
      - POSTGRES_DB=notebook_search
    expose:
      - 5432
      # - 5433:80
    
  nginx: 
    build: ./nginx
    volumes: 
      - ./search_engine_app/static:/nginx_server/search_engine_app/static
    networks: 
      - search_engine_net
    depends_on:
      - search_engine_app
    ports: 
      - 80:80

networks: 
  search_engine_net:
    driver: bridge

