services:
  elasticsearch: 
    build: ./elasticsearch
    volumes: 
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    environment:
      - discovery.type=single-node
      - cluster.name=es_dataserver
      - node.name=es01
    # expose: 
    #   - 9200
    # networks: 
    #   - search_engine_net
    ports:
      - 9200:9200

nginx: 
    build: ./nginx
    volumes: 
      - ./search_engine_app/static:/nginx_server/search_engine_app/static
    # networks: 
    #   - search_engine_net
    # depends_on:
    #   - search_engine_app
    ports: 
      - 80:80

#   search_engine_app:
#     build: ./search_engine_app
#     volumes:
#       - ./search_engine_app:/search_engine_app
#     networks: 
#       - search_engine_net
#     depends_on:
#       - elasticsearch
#     command: python manage.py runserver 0.0.0.0:7777
#     ports: 
#       - 7777:7777

# networks: 
#   search_engine_net:
#     driver: bridge


