services:
  postgres:
    image: postgres:14.5-bullseye
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/logs:/var/lib/postgresql/logs
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=notebooksearch2022
      - POSTGRES_DB=notebooksearch
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:6.14
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@notebooksearch.com
      - PGADMIN_DEFAULT_PASSWORD=notebooksearch2022
    volumes:
      - ./postgres/pgadmin:/var/lib/pgadmin
    depends_on: 
      - postgres

    

