services:
  elasticsearch: 
    build: ./elasticsearch
    image: local_test/elasticsearch
    container_name: local_test/elasticsearch
    volumes: 
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    environment:
      - discovery.type=single-node
      - cluster.name=es_dataserver
      - node.name=es01
      - TAKE_FILE_OWNERSHIP=true 
    ports:
      - 9200:9200


