services:
  postgres:
    build: ./postgres
    image: local_test/postgres
    container_name: local_test/postgres
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/logs:/var/lib/postgresql/logs
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=notebooksearch2022
      - POSTGRES_DB=notebook_search
    ports:
      - 5432:5432
