services:
  postgres:
    build: ./postgres
    image: local_test/postgres
    container_name: local_test_postgres
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/logs:/var/lib/postgresql/logs
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=notebooksearch2022
      - POSTGRES_DB=notebooksearch
    ports:
      - 5432:5432

  pgadmin:
    build: ./pgadmin
    image: local_test/pgadmin
    container_name: local_test_pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@notebooksearch.com
      - PGADMIN_DEFAULT_PASSWORD=notebooksearch2022
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    depends_on: 
      - postgres
    ports:
      - 5050:80

    

