# docker-compose_crawler.yml
# Build and run docker containers for notebook crawler
version: '2'
services:
    mongo:
        hostname: mongo
        image: mongo:5
        volumes:
            - ./mongo/db:/data/db
        ports:
            - 27017:27017