# Generated by Django 4.0.5 on 2022-10-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KaggleNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(default='No description.')),
                ('html_url', models.CharField(default='No html URL.', max_length=240)),
                ('kaggle_id', models.CharField(max_length=60)),
                ('file_name', models.CharField(max_length=60)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotebookSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=240)),
                ('facets', models.CharField(max_length=60)),
                ('num_hits', models.IntegerField()),
                ('num_pages', models.IntegerField()),
                ('current_page', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotebookSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=240)),
                ('timestamp', models.CharField(max_length=60)),
                ('event', models.CharField(max_length=60)),
                ('query', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=240)),
                ('research_interests', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
