# 
# LogUI Server docker-compose File
# 
# Author: David Maxwell
# Date: 2021-03-26
#

version: "3.0"

services:
  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - http-worker
      - websocket-worker
    ports:
      - ${PROXY_LISTEN_ON}:6110
    volumes:
      - static:/logui/worker/static/
    networks:
      - frontend

  http-worker:
    build:
      context: ./
      dockerfile: ./worker/Dockerfile
      args:
        - SECRET_KEY=${SECRET_KEY}  # This is required for collectstatic to work.
    env_file: .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - static:/logui/worker/static/
    networks:
      - frontend
      - backend
  
  websocket-worker:
    build:
      context: ./
      dockerfile: ./worker/Dockerfile
      args:
        - SECRET_KEY=${SECRET_KEY}
    command: daphne -b 0.0.0.0 -p 6110 worker.asgi:logui_application
    env_file: .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - static:/logui/worker/static/
    networks:
      - frontend
      - backend
  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=logui
      # - PGDATA=/logui/data/
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
  
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - mongo:/data/db
      - mongo:/data/configdb
    networks:
      - backend

volumes:
  static:
  db:
  mongo:

networks:
  frontend:
  backend: