FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.6 
# This is the default working dir
WORKDIR /usr/share/elasticsearch 

# Override the elasticsearch.yml file
ADD ./config/elasticsearch.yml /config/elasticsearch.yml
