# Generated by Django 4.0.5 on 2022-10-13 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubNotebookResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notebook_id', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(default='No description.')),
                ('html_url', models.CharField(default='No html URL.', max_length=240)),
                ('download_url', models.CharField(default='No download URL.', max_length=240)),
                ('full_name', models.CharField(max_length=60)),
                ('stargazers_count', models.IntegerField()),
                ('forks_count', models.IntegerField()),
                ('size', models.IntegerField()),
                ('language', models.CharField(max_length=60)),
                ('git_url', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KaggleNotebookResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notebook_id', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(default='No description.')),
                ('html_url', models.CharField(default='No html URL.', max_length=240)),
                ('download_url', models.CharField(default='No download URL.', max_length=240)),
                ('title', models.CharField(max_length=120)),
                ('kaggle_id', models.CharField(max_length=60)),
                ('file_name', models.CharField(max_length=60)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContextSearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotebookSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=60)),
                ('event', models.CharField(choices=[('notebook_search', 'notebook_search'), ('query_generation', 'query_generation'), ('context_based_search', 'context_based_search')], default='unknown', max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotebookSearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=60)),
                ('event', models.CharField(choices=[('notebook_search', 'notebook_search'), ('query_generation', 'query_generation'), ('context_based_search', 'context_based_search')], default='unknown', max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=60)),
                ('research_interests', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelevancyFeedbackRequest',
            fields=[
                ('notebooksearchrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notebook_search.notebooksearchrequest')),
                ('num_stars', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('notebook_search.notebooksearchrequest',),
        ),
    ]
