FROM postgres:14.1-alpine
# FROM dpage/pgadmin4:6.14
# This is the default working dir
WORKDIR /var/lib/postgresql/

# # Override the elasticsearch.yml file
# ADD ./config/elasticsearch.yml /config/elasticsearch.yml

# FROM dpage/pgadmin4:6.14
# WORKDIR /var/lib/pgadmin/
