FROM postgres:14.5-bullseye

# This is the default working dir
WORKDIR /var/lib/postgresql/

# Create a DATABASE named notebook_search
# RUN psql --username aubergine
# # RUN sudo -u posgres psql
# RUN CREATE DATABASE notebook_search;

# # Override the elasticsearch.yml file
# ADD ./config/elasticsearch.yml /config/elasticsearch.yml

# FROM dpage/pgadmin4:6.14
# WORKDIR /var/lib/pgadmin/
